source/routes/backend.php
<?php

Auth::routes();

Route::group(['prefix' => 'admin', 'namespace' => 'Auth', 'middleware' => 'web'], function () {
    //login
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@postLogin');
    //logout
    Route::get('logout', 'LoginController@logout')->name('logout');
    
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function () {
    //active user
    Route::get('/active-user/{token}', 'UsersController@activeUser')->name('user.active');
    Route::get('/change-password/{token}', 'UsersController@changePassword')->name('user.change-password');
    Route::post('/change-password/{token}', 'UsersController@postChangePassword')->name('user.change-password');
    
    //multi languages 
    Route::get('lang/{lang}','LangController@changeLang')->name('lang');
});

//403 permission
Route::get('admin/not-found', function () {
    return view('Backend.Errors.404');
})->name('notFound');

//404 not found
Route::get('admin/403', function () {
    return view('Backend.Errors.403');
})->name('403');


Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'middleware' => 'auth'], function () {
    Route::get('/', 'BackendController@index')->name('dashboard');

    //customer
    Route::get('/khach-hang', 'CustomerController@index')->name('customer.index');
    Route::get('/khach-hang/{id}', 'CustomerController@show')->name('customer.show');

    //product
    Route::resource('/product', 'ProductController');
    Route::get('export', 'ProductController@export')->name('product.export');

    //category
    Route::resource('/category', 'CategoryController');

    //recipes
    Route::resource('/recipe', 'RecipesController');

    //contact
    Route::resource('/contact', 'ContactController');

    //orders
    Route::resource('/order', 'OrdersController');

    //payment
    Route::resource('/payment', 'PaymentController');

    //shipper
    Route::resource('/shipper', 'ShipperController');

    //role
    Route::resource('/role', 'RoleController');

    //user
    Route::resource('/user', 'UsersController');
    Route::post('/user/change-password/{id}', 'UsersController@changePass')->name('user.changePass');

    //system information
    Route::get('/system/info', 'SystemController@index')->name('system.index');
});

source/routes/web.php
<?php

Route::group(['namespace' => 'Frontend', 'middleware' => 'web'], function () {
      Route::get('/', 'HomeController@index')->name('index');
      Route::post('/cart', 'HomeController@addToCart')->name('addToCart');

      //search
      Route::get('/search', 'HomeController@searchByName')->name('search');

      //introduction
      Route::get('/gioi-thieu', 'IntroductionController@index')->name('intro');

      //Product
      Route::get('/tat-ca-san-pham', 'ProductController@index')->name('product');
      Route::get('danh-muc/{id}', 'ProductController@listCake')->name('listCake');
      Route::get('/san-pham/{slug}', 'ProductController@detailProduct')->name('detailProduct');

      //Recipe
      Route::get('/cong-thuc', 'RecipesController@index')->name('recipe');
      Route::get('/cong-thuc/{id}', 'RecipesController@detailRecipe')->name('detailRecipe');
      Route::post('/cong-thuc/comment', 'RecipesController@comment')->name('commentRecipe');

      //Contact
      Route::get('/lien-he', 'ContactController@index')->name('contact');
      Route::post('/lien-he', 'ContactController@store')->name('contact');
      Route::view('/thankyou', 'Frontend/Contact/thanks');

      //login and register
      Route::get('/dang-nhap', 'LoginController@login')->name('dang_nhap');
      Route::post('/dang-nhap', 'LoginController@postLogin')->name('dang_nhap');
      Route::get('/dang-ky', 'LoginController@register')->name('dang_ky');
      Route::post('/dang-ky', 'LoginController@postRegister')->name('dang_ky');
      Route::get('/name/{id}', 'LoginController@checkName');
      Route::get('/dang_xuat', 'LoginController@logout')->name('dang_xuat');
      Route::get('/active-customer/{token}', 'LoginController@activeCustomer')->name('dang_nhap.active');


      //cart
      Route::get('/gio-hang', 'CartController@index')->name('cart.index');
      Route::get('/empty', function(){
          \Cart::destroy();
      });
      Route::delete('/{id}', 'CartController@destroy')->name('cart.destroy');
      Route::patch('gio-hang/{id}', 'CartController@update')->name('cart.update');
      Route::get('/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('customer');
      Route::post('/checkout', 'CartController@postCheckout')->name('cart.checkout');
      Route::get('/name/{id}', 'CartController@loadName');

    //   lịch sử đơn hàng
    Route::resource('history', 'HistoryOrderController');
});

source/app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    public function index()
    {
    	$users = \App\Model\Users::where(\DB::raw("(DATE_FORMAT(created_at,'%Y'))"),date('Y'))
    				->get();
        $chart = \Charts::database($users, 'bar', 'highcharts')
			      ->title("Monthly new Register Users")
			      ->elementLabel("Total Users")
			      ->dimensions(1000, 500)
			      ->responsive(false)
			      ->groupByMonth(date('Y'), true);
			      
        return view('Backend.dashboard.index', compact('chart'));
    }
}

source/app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Category\CategoryInterface;
use App\Http\Requests\CategoryRequest;
use DB;
use Auth;

class CategoryController extends Controller
{
    private $category;

    public function __construct(
        CategoryInterface $category
    ) {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $this->authorize('view-category');
        } catch (\Exception $e) {
            abort(403);
        }

        $category = $this->category->getListCategory();
       
        return view('Backend.Category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Backend.Category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $id = Auth::user()->id;
        $dataFormRequest = [
            'name' => $request->category_name,
            'user_id' => $id
        ];

        try {
            DB::beginTransaction();
            $category = $this->category->create($dataFormRequest);
            DB::commit();
            return redirect()->route('category.index')->with('success', sprintf(config('message.create_success'), 'Danh mục'))->withInput();
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()->with('error', sprintf(config('message.create_failed'), 'danh mục'))->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->getEditCategory($id);

        return view('Backend.Category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $dataFormRequest = [
            'name' => $request->category_name
        ];

        try {
            DB::beginTransaction();
            $this->category->update($dataFormRequest, $id);
            DB::commit();

            return redirect()->route('category.index')->with('success', sprintf(config('message.update_success'), 'Danh mục'))->withInput();
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()->with('error', sprintf(config('message.update_failed'), 'danh mục'))->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $message = config('message');
            $category = $this->category->getById($id);
            $user = Auth::user();

            if ($user->role_id !== 1 && $category->user_id !== $user->id) {
                return response()->json(['status_code' => 401, 'message' => $message['delete_permission_denied']]);
            }

            //update delet_flag
            $this->category->update(['deleted_flag' => 1], $id);
            return response()->json(['status_code' => 200, 'message' => $message['delete_success']]);
        } catch (Exception $ex) {
            return response()->json(['status_code' => 500, 'message' => $message['internal_server_error']]);
        }
    }
}

source/app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Contact\ContactInterface;
use App\Mail\sendMailContact;
use Mail;
use DB;
use Auth;
use App\Http\Requests\ContactBackendRequest;

class ContactController extends Controller
{

    private $contact;

    public function __construct(ContactInterface $contact){
        $this->contact=$contact;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $this->authorize('view-contact');
        } catch (\Exception $e) {
            abort(403);
        }

        $contacts = $this->contact->getListContact();

        return view('Backend.Contact.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('Backend.Contact.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contact = $this->contact->detailContact($id);
        return view('Backend.Contact.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ContactBackendRequest $request, $id)
    {
        $full_name = $request->full_name;
        $email = $request->email;
        $phone = $request->phone;
        $content = $request->content;
        $content_reply = $request->content_reply;

        $data = [
            'content_reply' => $request->content_reply
        ];
        
        try{
            DB::beginTransaction();
            $this->contact->update($data, $id);
            dispatch(new \App\Jobs\mailContact($full_name, $email, $phone, $content, $content_reply));
            DB::commit();
            return redirect()->route('contact.index')->with('success', 'Đã trả lời thành công')->withInput();
        }catch(\Exception $e) {
            DB::rollBack();
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $message = config('message');
            $contact = $this->contact->getById($id);
            $user = Auth::user();

            if ($user->role_id !== 1) {
                return response()->json(['status_code' => 401, 'message' => $message['delete_permission_denied']]);
            }

            //update delet_flag
            $this->contact->update(['deleted_flag' => 1], $id);
            return response()->json(['status_code' => 200, 'message' => $message['delete_success']]);
        } catch (Exception $ex) {
            return response()->json(['status_code' => 500, 'message' => $message['internal_server_error']]);
        }
    }
}

source/app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Customer\CustomerInterface;

class CustomerController extends Controller
{

    private $customer;

    public function __construct
    (
        CustomerInterface $customer
    )
    {
        $this->customer = $customer;
    }
    public function index()
    {
        try {
            $this->authorize('view-customer');
        } catch (\Exception $e) {
            abort(403);
        }

        $customer = $this->customer->getListCustomer();

        return view('Backend.Customer.index', compact('customer'));
    }

    public function show($id)
    {
        $customer = $this->customer->detailCustomer($id);

        if(empty($customer)) {
            abort(404);
        }
        return view('Backend.Customer.show', compact('customer'));
    }
}

source/app/Http/Controllers/Backend/LangController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LangController extends Controller
{
    private $langActive = [
        'vi',
        'en',
    ];
    
    public function changeLang(Request $request, $lang)
    {
        if (in_array($lang, $this->langActive)) {
            $request->session()->put(['lang' => $lang]);
            return redirect()->back();
        }
    }
}

source/app/Http/Controllers/Backend/OrdersController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Orders\OrdersInterface;
use App\Repositories\Customer\CustomerInterface;

class OrdersController extends Controller
{

    private $order;
    private $customer;

    public function __construct
    (
        OrdersInterface $order,
        CustomerInterface $customer
    )
    {
        $this->order = $order;
        $this->customer = $customer;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $this->authorize('view-order');
        } catch (\Exception $e) {
            abort(403);
        }

        $order = $this->order->getlistOrder();

        return view('Backend.Orders.index', compact('order'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $detail = $this->order->detailOrders($id);
        $customer = $this->customer->detailCustomer($id);
        if(empty($detail)) {
            \abort(404);
        }
        return view('Backend.Orders.show', compact('detail', 'customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

source/app/Http/Controllers/Backend/SystemController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SystemController extends Controller
{
    public function index()
    {
        return view('Backend.System.index');
    }
}

source/resources/views/Backend/Orders/index.blade.php
@extends('Backend.Layouts.master')

@section('title')
	<title>Đơn hàng | LuzBakery</title>
@stop()

@section('content')
	<section class="content">
        <ul class="breadcrumb">
		  <li>
		  	<a href="{{ route('dashboard') }}">
		  		<i class="fa fa-home" aria-hidden="true"></i>
		  	 	Bảng điểu khiển
		  	</a>
		  </li>
		  <li>
		  	Đơn hàng
		  </li>
		</ul>
		<div class="row">
			<div class="col-md-12 dataTable">
				<div class="box">
					<table id="table" class="table table-hover">
						<thead>
				            <tr>
				                <th>ID</th>
				                <th>Tên sản phẩm</th>
				                <th>Khách hàng</th>
				                <th>Tổng giá</th>
								<th>Trạng thái</th>
				                <th class="action">Tác vụ</th>
				            </tr>
				        </thead>
				        <tbody>
						@php $i=1; @endphp
						@foreach($order as $oder )
				            <tr>
				                <td class="vertical">{{ $i }}</td>
				                <td class="vertical">
				                	<a href="{{ route('order.show', $oder->id) }}">{{ $oder->product_name }}</a>
				                </td>
				                <td class="vertical">
				                	{{ $oder->first_name }} {{ $oder->last_name }}
				                </td>
				                <td class="vertical">
				                	{{ $oder->total_mount }} VNĐ
				                </td>
								<td class="vertical">
								@if($oder->status == 1)
									<button class="btn btn-sm waves-effect waves-light btn-rounded btn-outline-primary">Đã thanh toán</button>
								@else
									<button class="btn btn-sm btn-outline-danger">Pending</button>
								@endif	
								</td>
				                <td class="vertical">
				                	<a href="{{ route('order.show', $oder->id) }}" class="btn btn-sm waves-effect waves-light btn-warning">Xem</a>
				                	<a class="btn btn-sm btn-outline-danger btn-delete">Xóa</a>
				                </td>
				            </tr>
						@php $i++; @endphp	
						@endforeach
				        </tbody>
					</table>
				</div>
			</div>
		</div>
	</section>
@stop()

source/resources/views/Backend/Orders/show.blade.php
@extends('Backend.Layouts.master')

@section('title')
	<title>Đơn hàng | LuzBakery</title>
@stop()

@section('content')
	<section class="content">
        <ul class="breadcrumb">
		  <li>
		  	<a href="{{ route('dashboard') }}">
		  		<i class="fa fa-home" aria-hidden="true"></i>
		  	 	Bảng điểu khiển
		  	</a>
		  </li>
		  <li>
		  	<a href="{{ route('order.index') }}">Đơn hàng</a>
		  </li>
		  <li>
		  	Chi tiết đơn hàng
		  </li>
		</ul>
		<div class="pad margin no-print">
	      <div class="callout callout-info" style="margin-bottom: 0!important;">
	        <h4><i class="fa fa-info"></i> Note:</h4>
	        Nhấn vào nút in ở cuối hóa đơn để kiểm tra
	      </div>
	    </div>
		<div class="row">
			<div class="col-md-12 dataTable">
				<section class="invoice">
			      <!-- title row -->
			      <div class="row">
			        <div class="col-xs-12">
			          <h2 class="page-header">
			            <i class="fa fa-globe"></i> {{ $detail->first_name }} {{ $detail->last_name }}
			            <small class="pull-right">Date: {{ $detail->created_at }}</small>
			          </h2>
			        </div>
			        <!-- /.col -->
			      </div>
			      <!-- info row -->
			      <div class="row invoice-info">
			        <div class="col-sm-4 invoice-col">
			          Từ
			          <address>
			            <strong>{{ $detail->first_name }} {{ $detail->last_name }}, Inc.</strong><br>
			            {{ $detail->address }}<br>
			            Số điện thoại: {{ $detail->phone }}<br>
			            Email: {{ $detail->email }}
			          </address>
			        </div>
			        <!-- /.col -->
			        <div class="col-sm-4 invoice-col">
			          Tới
			          <address>
			            <strong>{{ $detail->first_name }} {{ $detail->last_name }}</strong><br>
			            {{ $customer->district_name }} {{ $customer->province_name }}<br>
			            Số điện thoại: {{ $detail->phone }}<br>
			            Email: {{ $detail->email }}
			          </address>
			        </div>
			        <!-- /.col -->
			        <div class="col-sm-4 invoice-col">
			          <b>Hóa đơn #OD-00{{$detail->id}}</b><br>
			          <br>
			          <b>ID:</b> {{$detail->id}}<br>
			          <b>Ngày thanh toán:</b>{{$detail->updated_at}}<br>
			        </div>
			        <!-- /.col -->
			      </div>
			      <!-- /.row -->

			      <!-- Table row -->
			      <div class="row">
			        <div class="col-xs-12 table-responsive">
			          <table class="table table-striped">
			            <thead>
							<tr>
								<th>STT</th>
								<th>Tên sản phẩm</th>
								<th>Giá tiền</th>
								<th>Số lượng</th>
								<th>Tổng tiền</th>
							</tr>
			            </thead>
			            <tbody>
							<tr>
								<td>1</td>
								<td>{{ $detail->product_name }}</td>
								<td>{{ number_format(empty($detail->sale_price) ? $detail->price : $detail->sale_price, 3) }} VNĐ</td>
								<td>{{ $detail->qty }}</td>
								<td>{{ $detail->total_mount }} VNĐ</td>
							</tr>
			            </tbody>
			          </table>
			        </div>
			        <!-- /.col -->
			      </div>
			      <!-- /.row -->

			      <div class="row">
			        <!-- accepted payments column -->
			        <div class="col-xs-6">
			          <p class="lead">Phương thức thanh toán:</p>
			          <img src="{{ asset('backend/image/visa.png')}}" alt="Visa">
			        </div>
			        <!-- /.col -->
			        <div class="col-xs-6">
			          <p class="lead">Tổng tiền</p>

			          <div class="table-responsive">
			            <table class="table">
			              <tbody>
			              <tr>
			                <th>Thành tiền:</th>
			                <td>{{ $detail->total_mount }} VNĐ</td>
			              </tr>
			            </tbody></table>
			          </div>
			        </div>
			        <!-- /.col -->
			      </div>
			      <!-- /.row -->

			      <!-- this row will not appear when printing -->
			      <div class="row no-print">
			        <div class="col-xs-12">
			          <a href="javascript:void(0)" target="_blank" class="btn btn-default" onClick="window.print()"><i class="fa fa-print"></i> Print</a>
			        </div>
			      </div>
			    </section>
			</div>
		</div>
	</section>
@stop()