source/routes/backend.php
<?php

Auth::routes();

Route::group(['prefix' => 'admin', 'namespace' => 'Auth', 'middleware' => 'web'], function () {
    //login
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@postLogin');
    //logout
    Route::get('logout', 'LoginController@logout')->name('logout');
    
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function () {
    //active user
    Route::get('/active-user/{token}', 'UsersController@activeUser')->name('user.active');
    Route::get('/change-password/{token}', 'UsersController@changePassword')->name('user.change-password');
    Route::post('/change-password/{token}', 'UsersController@postChangePassword')->name('user.change-password');
    
    //multi languages 
    Route::get('lang/{lang}','LangController@changeLang')->name('lang');
});

//403 permission
Route::get('admin/not-found', function () {
    return view('Backend.Errors.404');
})->name('notFound');

//404 not found
Route::get('admin/403', function () {
    return view('Backend.Errors.403');
})->name('403');


Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'middleware' => 'auth'], function () {
    Route::get('/', 'BackendController@index')->name('dashboard');

    //customer
    Route::get('/khach-hang', 'CustomerController@index')->name('customer.index');
    Route::get('/khach-hang/{id}', 'CustomerController@show')->name('customer.show');

    //product
    Route::resource('/product', 'ProductController');
    Route::get('export', 'ProductController@export')->name('product.export');

    //category
    Route::resource('/category', 'CategoryController');

    //recipes
    Route::resource('/recipe', 'RecipesController');

    //contact
    Route::resource('/contact', 'ContactController');

    //orders
    Route::resource('/order', 'OrdersController');

    //payment
    Route::resource('/payment', 'PaymentController');

    //shipper
    Route::resource('/shipper', 'ShipperController');

    //role
    Route::resource('/role', 'RoleController');

    //user
    Route::resource('/user', 'UsersController');
    Route::post('/user/change-password/{id}', 'UsersController@changePass')->name('user.changePass');

    //system information
    Route::get('/system/info', 'SystemController@index')->name('system.index');
});

source/routes/web.php
<?php

Route::group(['namespace' => 'Frontend', 'middleware' => 'web'], function () {
      Route::get('/', 'HomeController@index')->name('index');
      Route::post('/cart', 'HomeController@addToCart')->name('addToCart');

      //search
      Route::get('/search', 'HomeController@searchByName')->name('search');

      //introduction
      Route::get('/gioi-thieu', 'IntroductionController@index')->name('intro');

      //Product
      Route::get('/tat-ca-san-pham', 'ProductController@index')->name('product');
      Route::get('danh-muc/{id}', 'ProductController@listCake')->name('listCake');
      Route::get('/san-pham/{slug}', 'ProductController@detailProduct')->name('detailProduct');

      //Recipe
      Route::get('/cong-thuc', 'RecipesController@index')->name('recipe');
      Route::get('/cong-thuc/{id}', 'RecipesController@detailRecipe')->name('detailRecipe');
      Route::post('/cong-thuc/comment', 'RecipesController@comment')->name('commentRecipe');

      //Contact
      Route::get('/lien-he', 'ContactController@index')->name('contact');
      Route::post('/lien-he', 'ContactController@store')->name('contact');
      Route::view('/thankyou', 'Frontend/Contact/thanks');

      //login and register
      Route::get('/dang-nhap', 'LoginController@login')->name('dang_nhap');
      Route::post('/dang-nhap', 'LoginController@postLogin')->name('dang_nhap');
      Route::get('/dang-ky', 'LoginController@register')->name('dang_ky');
      Route::post('/dang-ky', 'LoginController@postRegister')->name('dang_ky');
      Route::get('/name/{id}', 'LoginController@checkName');
      Route::get('/dang_xuat', 'LoginController@logout')->name('dang_xuat');
      Route::get('/active-customer/{token}', 'LoginController@activeCustomer')->name('dang_nhap.active');


      //cart
      Route::get('/gio-hang', 'CartController@index')->name('cart.index');
      Route::get('/empty', function(){
          \Cart::destroy();
      });
      Route::delete('/{id}', 'CartController@destroy')->name('cart.destroy');
      Route::patch('gio-hang/{id}', 'CartController@update')->name('cart.update');
      Route::get('/checkout', 'CartController@checkout')->name('cart.checkout')->middleware('customer');
      Route::post('/checkout', 'CartController@postCheckout')->name('cart.checkout');
      Route::get('/name/{id}', 'CartController@loadName');

    //   lịch sử đơn hàng
    Route::resource('history', 'HistoryOrderController');
});

source/resources/views/Backend/Product/Component/list/listIndex.blade.php
<thead>
    <tr>
        <th>ID</th>
        <th>Tên sản phẩm</th>
        <th>Hình ảnh</th>
        <th>Giá sản phẩm</th>
        <th>Giá khuyến mại</th>
        <th>Số lượng</th>
        <th>Danh mục</th>
        <th class="action">Tác vụ</th>
    </tr>
</thead>
<tbody>
    @if(!empty($product))
    @php $i=1; @endphp
    @foreach($product as $pro)
    <tr>
        <td class="vertical">{{ $i }}</td>
        <td class="vertical">
          <a href="{{ route('product.show', $pro->id) }}">{{ $pro->product_name }}</a>
        </td>
        <td>
          <div class="product_image">
            <img src="{{ $pro->image }}" alt="{{ $pro->product_name }}">
          </div>
        </td>
        @if(!empty($pro->sale_price))
            <td class="vertical" style="text-decoration: line-through">{{ number_format($pro->price, 2, ',', '.') }} VNĐ</td>
        @else
            <td class="vertical">{{ number_format($pro->price, 2, ',', '.') }} VNĐ</td>
        @endif
        @if(!empty($pro->sale_price))
            <td class="vertical">{{ number_format($pro->sale_price, 2, ',', '.') }} VNĐ</td>
        @else
            <td class="vertical">0 VNĐ</td>
        @endif
        <td class="vertical">{{ $pro->qty }}</td>
        <td class="vertical">
          <button class="btn btn-sm waves-effect waves-light btn-rounded btn-outline-primary">{{ $pro->name }}</button>
        </td>
        <td class="vertical">
          <a href="{{ route('product.edit', $pro->id) }}" class="btn btn-sm waves-effect waves-light btn-warning">@lang('all.edit')</a>
          <a href="javascript:void(0)" class="btn btn-sm btn-outline-danger btn-delete"  data-url="{{ route('product.destroy', $pro->id) }}" data-url-reload="{{ route('product.index', $pro->id) }}">@lang('all.delete')</a>
        </td>
    </tr>
    @php $i++; @endphp
    @endforeach()
    @endif
</tbody>